### PR TITLE
Fix data read by splitting into all, stage and non-stage

### PR DESCRIPTION
**Pull request by shankari**
- split out uuids into all, stage and non stage
- fixed the uuid check to split the confirmed trips also into stage and non stage
- found missing IDs and confirmed that they had no data
- created confirmed and expanded confirmed trips dataframes separately for stage and non stage as well

### CODE REVIEW

**Comment by shankari** [comment]
@zackAemmer I also think that the inferred label code is incorrect but wanted to get this done first.

**Comment by shankari** [comment]
As I indicated in the notebook comments, I don't think it is correct to include the inferred labels as mode_confirm and use it naively as input to something like random forest. The inferred labels are also the outputs of an algorithm with its own error.

So I commented out the code to fill in the inferred labels and re-ran to see the results. As expected, they were slightly worse. HOWEVER, the proportion of correctly stated replacement modes went to 100%

image

image

image

This is a little surprising since the inferred labels are based on prior labels, so they should not be wrong unless there was an original incorrect label, which should show up here. I wonder if the incorrect labels are just getting swamped by the NA values.

I'm going to take a break now and return to this tomorrow morning.

**Comment by shankari** [comment]
> This is a little surprising since the inferred labels are based on prior labels, so they should not be wrong unless there was an original incorrect label, which should show up here. I wonder if the incorrect labels are just getting swamped by the NA values.

I tried filtering out the N/A

```
>>> expanded_ct = scaffolding.filter_labeled_trips(expanded_ct)
After filtering, found 57729 labeled trips
```

Results are the same.

I now wonder if the mapping with the inferred mode was messed up because some trips did not have an inferred mode

**Comment by shankari** [comment]
Added a check for the inferred labels, and it looks like the inferred mode is always None

The check that I added 

```
# Let's check whether the inferred mode is filled in correctly
# https://github.com/zackAemmer/em-public-dashboard/pull/1#issuecomment-1198195501

for i, im in enumerate(inferred_modes):
    print(f"Checking {im} at {i}")
    if im is None:
        print(f"Found no inferred mode at {i}, dataframe entry is %s" % with_inferred_ct.iloc[i].mode_confirm)
```

prints out every single entry

```
Found no inferred mode at 0, dataframe entry is drove_alone
Found no inferred mode at 1, dataframe entry is drove_alone
Found no inferred mode at 2, dataframe entry is drove_alone
Found no inferred mode at 3, dataframe entry is drove_alone
Found no inferred mode at 4, dataframe entry is drove_alone
Found no inferred mode at 5, dataframe entry is drove_alone
Found no inferred mode at 6, dataframe entry is drove_alone
Found no inferred mode at 7, dataframe entry is drove_alone
Found no inferred mode at 8, dataframe entry is None
Found no inferred mode at 9, dataframe entry is None
```

And stepping back

```
# Apply label assist mode where not filled in

inferred_modes = []
for i in range(0,len(expanded_ct)):
    try:
        inferred_modes.append(expanded_all_ct['inferred_labels'].iloc[i][0]['labels']['mode_confirm'])
    except:
        inferred_modes.append(None)

print(inferred_modes[0:10])
        
with_inferred_ct = expanded_ct.copy()
with_inferred_ct['Inferred_mode'] = inferred_modes
with_inferred_ct.mode_confirm.fillna(with_inferred_ct.Inferred_mode, inplace=True)
```
prints

```
[None, None, None, None, None, None, None, None, None, None]
```

**Comment by shankari** [comment]
@zackAemmer  one more fix (for the inferred labels check)

**Comment by zackAemmer** [comment]
> As I indicated in the notebook comments, I don't think it is correct to include the inferred labels as mode_confirm and use it naively as input to something like random forest. The inferred labels are also the outputs of an algorithm with its own error.
> 
> So I commented out the code to fill in the inferred labels and re-ran to see the results. As expected, they were slightly worse. HOWEVER, the proportion of correctly stated replacement modes went to 100%
> 
> image
> 
> image
> 
> image
> 
> This is a little surprising since the inferred labels are based on prior labels, so they should not be wrong unless there was an original incorrect label, which should show up here. I wonder if the incorrect labels are just getting swamped by the NA values.
> 
> I'm going to take a break now and return to this tomorrow morning.

For this one there is a line in the data processing section that puts the replaced mode in the choice set, and has to be flipped depending on if you want to see the replaced mode visualizations, or have the models trained with the replacement modes as available:
`if mode in options or mode==choice_list[i] or mode==replaced_list[i]:`

**Comment by shankari** [comment]
> For this one there is a line in the data processing section that puts the replaced mode in the choice set, and has to be flipped depending on if you want to see the replaced mode visualizations, or have the models trained with the replacement modes as available:

Cool! Will try that out.

Note, however, that I am not sure that the inferred labels were ever filled in? Unless I am missing something else where as well..

**Comment by shankari** [comment]
> Cool! Will try that out.

Tried it out, can confirm that the visualizations do show up now.

**Comment by zackAemmer** [comment]
So I did all of that analysis with the inferred labels yesterday, the models originally did not use the inferred labels at all. One thing I don't understand is whether the inferred labels == the sensed labels. I remember we wanted to include the sensed labels, and I thought that this function was removing the sensed trips:

`scaffolding.filter_labeled_trips()`

But then yesterday I realized that a TON of trips were NaN for their mode_confirm, which then gets labeled as Other for Mode_confirm, which then leads to them being dropped. I saw this and thought I must be doing it wrong, and should use the inferred labels as the sensed labels. Looks like I managed to do that wrong as well though! I am very happy to not use the inferred labels, if that is the most principled approach.

**Comment by shankari** [comment]
>  If we just want to see how many user-specified replaced_mode labels are in the surveyed availability set, we can just compare it directly, right? We don't need to build a model first?

To answer my own question, it looks like you have loaded the data into a biogeme database and for simplicity, are just using that database throughout. We could do it without biogeme, but it is easier to work with the data that we already have...

**Comment by zackAemmer** [comment]
> @zackAemmer I think I understand what that is doing, but I don't understand why it is needed.
> If we just want to see how many user-specified replaced_mode labels are in the surveyed availability set, we can just compare it directly, right? We don't need to build a model first?

I added the replaced mode to the availability set because the models need availability information to correctly predict the replaced mode (accuracy on replaced mode goes waayy down otherwise). For example someone states that their primary mode was ebike, replaced mode was car, stated availability is transit and walking. The models are trained on this and will basically never predict car (the discrete choice will 100% never predict it, the random forest might but is unlikely). So then we go and test them on the replaced mode and every single trip that is not in the availability set they predict incorrectly. You can swap this line out and run the models and see how low the accuracy goes. Hopefully I am understanding the question correctly

**Comment by shankari** [comment]
> But then yesterday I realized that a TON of trips were NaN for their mode_confirm, which then gets labeled as Other for Mode_confirm, which then leads to them being dropped. I saw this and thought I must be doing it wrong, and should use the inferred labels as the sensed labels. Looks like I managed to do that wrong as well though! I am very happy to not use the inferred labels, if that is the most principled approach.

There are two algorithms. The inferred labels are from the label assist, the sensed labels are actually not available at the trip level by default currently. you have to run Michael's script.

Let me handle incorporating the sensed labels with another switch flip since I know the OpenPATH data structure better.
That way, our primary analysis can be on the labeled trips, but we can also have some results for the sensed-only values.

**Pull request merged**
